#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PMA.Resource", IsApplication=true)]

namespace PMA
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::PMA.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int activity_horizontal_margin = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int activity_vertical_margin = 2131034113;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_appointment = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_login = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int edittext_password = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int edittext_username = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int logo_dextra = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int monoandroidsplash = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int password = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int progressbar = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int transparent_linearlayout = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int user = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int btnAppointment = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int btnLogin = 2131165191;
			
			// aapt resource value: 0x7f070003
			public const int chkAutoAppointment = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int etPass = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int etUserName = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int imgLogo = 2131165188;
			
			// aapt resource value: 0x7f070008
			public const int linearLayout = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int pbLogin = 2131165193;
			
			// aapt resource value: 0x7f070002
			public const int timeAppointment = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int txtEndOfJourney = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Appointment = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Configuration = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Login = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int LoginButton = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int LoginEditText = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int Mono_Android_Theme_Splash = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
